import type { DemoLanding } from "@/lib/demo-landings"

export const INDUSTRY_DEMO_LANDINGS: DemoLanding[] = [
  {
    slug: "logistics",
    category: "industry",
    clientType: "logistics",
    clientLabel: "Logistics company",
    brand: "NordFreight",
    eyebrow: "European freight · sample",
    headline: "Cross-border freight that arrives on time — every time.",
    subheadline:
      "Road, rail, and last-mile delivery across 24 countries. Real-time tracking, customs handled, and a team that picks up the phone.",
    cta: "Get a freight quote",
    ctaSecondary: "Track a shipment",
    features: [
      {
        title: "Live shipment tracking",
        description: "Clients and ops see the same status — ETA, delays, and proof of delivery in one portal.",
      },
      {
        title: "Customs & compliance",
        description: "Documentation, tariffs, and border clearance managed so goods keep moving.",
      },
      {
        title: "Dedicated fleet network",
        description: "Vetted carriers across Europe with SLAs you can put in a client contract.",
      },
    ],
    stats: [
      { value: "98%", label: "On-time delivery" },
      { value: "24", label: "Countries served" },
      { value: "500+", label: "Business clients" },
    ],
    steps: [
      { title: "Request a quote", description: "Route, cargo type, and timeline — answer in hours." },
      { title: "We handle the rest", description: "Pickup, customs, tracking, and delivery confirmation." },
      { title: "Invoice & repeat", description: "Clear billing and saved routes for recurring lanes." },
    ],
    testimonial: {
      quote: "We switched three lanes to NordFreight and cut delays by half. Their tracking portal alone saved our ops team hours.",
      author: "Marcus Weber",
      role: "Supply chain director · Industrial parts",
    },
    trustLogos: ["Maersk", "DHL", "DB Schenker", "FedEx", "CEVA", "Kuehne+Nagel"],
    theme: {
      bg: "#0a1628",
      surface: "#122240",
      border: "#1e3a5f",
      text: "#f0f6ff",
      muted: "#8ba3c7",
      primary: "#2563eb",
      primaryHover: "#3b82f6",
      primaryText: "#ffffff",
      accent: "#f97316",
    },
  },
  {
    slug: "pharma",
    category: "industry",
    clientType: "pharma",
    clientLabel: "Pharmaceutical company",
    brand: "PureVita Labs",
    eyebrow: "Life sciences · sample",
    headline: "Science-led therapies built on trust, compliance, and care.",
    subheadline:
      "From early research to GMP manufacturing — a partner for hospitals, distributors, and patients who need reliability above all.",
    cta: "Partner with us",
    ctaSecondary: "View pipeline",
    features: [
      {
        title: "GMP-certified production",
        description: "Manufacturing and quality systems aligned with EU and international standards.",
      },
      {
        title: "Clinical partnerships",
        description: "Collaboration with research hospitals and CROs from Phase I to market.",
      },
      {
        title: "Regulatory expertise",
        description: "Documentation, pharmacovigilance, and submission support built into delivery.",
      },
    ],
    stats: [
      { value: "15+", label: "Years in market" },
      { value: "12", label: "Approved products" },
      { value: "EU", label: "GMP certified" },
    ],
    steps: [
      { title: "Discovery call", description: "Understand therapeutic area, volume, and regulatory path." },
      { title: "Due diligence", description: "Quality audit, specs, and timeline agreed in writing." },
      { title: "Production & supply", description: "Batch release, logistics, and ongoing pharmacovigilance." },
    ],
    testimonial: {
      quote: "PureVita's documentation and batch traceability made our hospital procurement process straightforward — rare in this sector.",
      author: "Dr. Elena Kowalska",
      role: "Head of pharmacy · Regional hospital network",
    },
    trustLogos: ["EMA", "FDA", "WHO", "GMP", "ISO 13485", "Pharmaceutical Society"],
    theme: {
      bg: "#f8fafc",
      surface: "#ffffff",
      border: "#e2e8f0",
      text: "#0f172a",
      muted: "#64748b",
      primary: "#0d9488",
      primaryHover: "#14b8a6",
      primaryText: "#ffffff",
      accent: "#06b6d4",
    },
  },
  {
    slug: "events",
    category: "industry",
    clientType: "events",
    clientLabel: "Event company",
    brand: "Meridian Events",
    eyebrow: "Corporate & private events · sample",
    headline: "Events that feel effortless — and look unforgettable.",
    subheadline:
      "Product launches, conferences, and private celebrations. Full-service planning, production, and on-site execution across Europe.",
    cta: "Plan your event",
    ctaSecondary: "View past events",
    features: [
      {
        title: "End-to-end production",
        description: "Venue, AV, staging, catering, and run-of-show — one team, one contact.",
      },
      {
        title: "Premium venue network",
        description: "Access to rooftops, galleries, and conference spaces clients can't book alone.",
      },
      {
        title: "On-site event crew",
        description: "Experienced producers on the ground so you enjoy the moment, not manage it.",
      },
    ],
    stats: [
      { value: "350+", label: "Events delivered" },
      { value: "48h", label: "Concept turnaround" },
      { value: "100%", label: "Dedicated producer" },
    ],
    steps: [
      { title: "Brief & concept", description: "Goals, guest count, budget, and creative direction." },
      { title: "Design & confirm", description: "Moodboards, venue options, and supplier contracts." },
      { title: "Produce & deliver", description: "Build, rehearse, execute, and wrap — flawlessly." },
    ],
    testimonial: {
      quote: "Our product launch had 400 guests and zero visible stress. Meridian handled everything — we just showed up and presented.",
      author: "Sarah Lindholm",
      role: "Marketing director · B2B SaaS",
    },
    trustLogos: ["Google", "Spotify", "BMW", "Adobe", "Salesforce", "Red Bull"],
    theme: {
      bg: "#140f1a",
      surface: "#221830",
      border: "#3d2d52",
      text: "#faf5ff",
      muted: "#c4b5fd",
      primary: "#a855f7",
      primaryHover: "#c084fc",
      primaryText: "#ffffff",
      accent: "#fbbf24",
    },
  },
  {
    slug: "beauty",
    category: "industry",
    clientType: "beauty",
    clientLabel: "Beauty company",
    brand: "Lumière Studio",
    eyebrow: "Salon & spa · sample",
    headline: "Quiet luxury for skin, hair, and the hour you keep for yourself.",
    subheadline:
      "Award-winning stylists and therapists in the heart of the city. Book online, arrive calm, leave glowing.",
    cta: "Book an appointment",
    ctaSecondary: "View treatments",
    features: [
      {
        title: "Signature treatments",
        description: "Facials, colour, and body rituals designed by senior therapists — not off-the-shelf menus.",
      },
      {
        title: "Master stylists",
        description: "Consultation-first approach so every visit feels personal, not rushed.",
      },
      {
        title: "Online booking",
        description: "Pick your therapist, time slot, and treatment — confirmation in seconds.",
      },
    ],
    stats: [
      { value: "4.9", label: "Average rating" },
      { value: "12", label: "Senior stylists" },
      { value: "7", label: "Days a week" },
    ],
    steps: [
      { title: "Choose your treatment", description: "Browse services or book a free consultation." },
      { title: "Pick a time", description: "Real-time availability with your preferred stylist." },
      { title: "Arrive & unwind", description: "Complimentary consultation, treatment, and aftercare tips." },
    ],
    testimonial: {
      quote: "Finally a salon that doesn't feel chaotic. Booking online, beautiful space, and my colour has never looked this good.",
      author: "Amelia Rossi",
      role: "Regular client · Colour & facial",
    },
    trustLogos: ["Olaplex", "Dermalogica", "Kerastase", "Aesop", "SMA", "Vogue Beauty"],
    theme: {
      bg: "#1a1214",
      surface: "#2a1c20",
      border: "#4a3038",
      text: "#fdf2f4",
      muted: "#d4a5b0",
      primary: "#e11d48",
      primaryHover: "#f43f5e",
      primaryText: "#ffffff",
      accent: "#fda4af",
    },
  },
  {
    slug: "legal",
    category: "industry",
    clientType: "legal",
    clientLabel: "Law firm",
    brand: "Blackwood & Partners",
    eyebrow: "Corporate & commercial law · sample",
    headline: "Clear legal counsel when the stakes are high.",
    subheadline:
      "M&A, contracts, employment, and dispute resolution for growing businesses. Direct access to partners — not endless hand-offs.",
    cta: "Book a consultation",
    ctaSecondary: "Our practice areas",
    features: [
      {
        title: "Partner-led advice",
        description: "Senior lawyers on your matter from day one — no junior-only teams on complex deals.",
      },
      {
        title: "Business-first approach",
        description: "Practical guidance aligned with your timeline, risk tolerance, and commercial goals.",
      },
      {
        title: "Cross-border capability",
        description: "EU and UK matters handled with trusted local counsel where needed.",
      },
    ],
    stats: [
      { value: "25+", label: "Years combined" },
      { value: "200+", label: "Clients served" },
      { value: "24h", label: "Initial response" },
    ],
    steps: [
      { title: "Initial call", description: "Understand the matter, urgency, and desired outcome." },
      { title: "Scope & fee", description: "Clear engagement letter — fixed fee or capped where possible." },
      { title: "Resolve & support", description: "Execute the work and stay available for follow-up." },
    ],
    testimonial: {
      quote: "They explained our acquisition docs in plain language and closed on schedule. Exactly the kind of firm you want when money is on the line.",
      author: "Tomás Rivera",
      role: "CEO · B2B software company",
    },
    trustLogos: ["Legal 500", "Chambers", "IFLR1000", "Deloitte Legal", "Lex Mundi", "IBA"],
    theme: {
      bg: "#0c0f14",
      surface: "#151b24",
      border: "#2a3444",
      text: "#f1f5f9",
      muted: "#94a3b8",
      primary: "#1e3a5f",
      primaryHover: "#2563eb",
      primaryText: "#ffffff",
      accent: "#c9a227",
    },
  },
  {
    slug: "restaurant",
    category: "industry",
    clientType: "restaurant",
    clientLabel: "Restaurant group",
    brand: "Ember & Oak",
    eyebrow: "Fine dining & bistro · sample",
    headline: "Seasonal plates, warm service, reservations made simple.",
    subheadline:
      "Two locations in the city centre. Wood-fired mains, natural wine, and a dining room people come back to every month.",
    cta: "Reserve a table",
    ctaSecondary: "View menu",
    features: [
      {
        title: "Online reservations",
        description: "Book by date, party size, and location — instant confirmation, no phone tag.",
      },
      {
        title: "Seasonal menu",
        description: "Locally sourced ingredients with a menu that changes with the harvest.",
      },
      {
        title: "Private dining",
        description: "Semi-private rooms and set menus for teams, dates, and celebrations.",
      },
    ],
    stats: [
      { value: "4.8", label: "Google rating" },
      { value: "2", label: "City locations" },
      { value: "80", label: "Covers nightly" },
    ],
    steps: [
      { title: "Pick a date", description: "See live availability for lunch or dinner." },
      { title: "Choose your spot", description: "Main room, bar, or terrace — where available." },
      { title: "Arrive hungry", description: "Host greets you; kitchen handles the rest." },
    ],
    testimonial: {
      quote: "Best steak in town and booking took thirty seconds. We bring clients here because the whole experience feels considered.",
      author: "Julia Mensah",
      role: "Regular guest · Business dinners",
    },
    trustLogos: ["Michelin Guide", "TripAdvisor", "The Infatuation", "OpenTable", "Wolt", "Gault&Millau"],
    theme: {
      bg: "#14100c",
      surface: "#221a12",
      border: "#3d2e1e",
      text: "#fef7ed",
      muted: "#c9a882",
      primary: "#c2410c",
      primaryHover: "#ea580c",
      primaryText: "#ffffff",
      accent: "#fbbf24",
    },
  },
  {
    slug: "fitness",
    category: "industry",
    clientType: "fitness",
    clientLabel: "Fitness studio",
    brand: "Forge Athletics",
    eyebrow: "Strength & conditioning · sample",
    headline: "Train smarter. Get stronger. Stay consistent.",
    subheadline:
      "Small-group coaching, open gym, and personalised programmes — built for people who want results, not just a membership card.",
    cta: "Start free trial",
    ctaSecondary: "View classes",
    features: [
      {
        title: "Coach-led sessions",
        description: "Limited class sizes so form, progress, and safety actually get attention.",
      },
      {
        title: "Flexible memberships",
        description: "Monthly, class packs, or PT — pick what matches how you train.",
      },
      {
        title: "Progress tracking",
        description: "Benchmark workouts and check-ins so you see strength gains over time.",
      },
    ],
    stats: [
      { value: "500+", label: "Active members" },
      { value: "40+", label: "Classes weekly" },
      { value: "6", label: "Certified coaches" },
    ],
    steps: [
      { title: "Book a trial", description: "Free intro session with a coach — no pressure." },
      { title: "Get your plan", description: "Goals, schedule, and the right membership tier." },
      { title: "Show up & progress", description: "Train consistently with programming that adapts." },
    ],
    testimonial: {
      quote: "I tried three gyms before Forge. Here the coaches know my name and my deadlift actually went up 40 kg in six months.",
      author: "Chris Okafor",
      role: "Member · Strength programme",
    },
    trustLogos: ["CrossFit", "NASM", "Myzone", "Technogym", "WHOOP", "Fitbit"],
    theme: {
      bg: "#0a0f0a",
      surface: "#141a14",
      border: "#243024",
      text: "#ecfdf5",
      muted: "#86b89a",
      primary: "#16a34a",
      primaryHover: "#22c55e",
      primaryText: "#ffffff",
      accent: "#a3e635",
    },
  },
  {
    slug: "real-estate",
    category: "industry",
    clientType: "real-estate",
    clientLabel: "Real estate agency",
    brand: "Harbor & Co.",
    eyebrow: "Residential & commercial · sample",
    headline: "Find the right property — or sell yours for what it's worth.",
    subheadline:
      "Local market expertise, professional photography, and a team that responds fast. Apartments, family homes, and investment units.",
    cta: "View listings",
    ctaSecondary: "Get a valuation",
    features: [
      {
        title: "Curated listings",
        description: "Search by district, budget, and property type — updated daily.",
      },
      {
        title: "Seller representation",
        description: "Pricing strategy, staging advice, and negotiation until keys are handed over.",
      },
      {
        title: "Market insights",
        description: "Comparable sales and neighbourhood data so you decide with confidence.",
      },
    ],
    stats: [
      { value: "€240M", label: "Sold last year" },
      { value: "18", label: "Avg. days on market" },
      { value: "120+", label: "Active listings" },
    ],
    steps: [
      { title: "Tell us what you need", description: "Buy, sell, or rent — area, budget, timeline." },
      { title: "View or list", description: "Book viewings or launch your property with pro media." },
      { title: "Close with support", description: "Offers, contracts, and handover managed end-to-end." },
    ],
    testimonial: {
      quote: "Harbor sold our flat in two weeks above asking. Their valuation was spot-on and buyers loved the listing photos.",
      author: "Ewa Nowak",
      role: "Seller · 3-bedroom apartment",
    },
    trustLogos: ["Rightmove", "Zillow", "Idealista", "RICS", "NAR", "Immobiliare.it"],
    theme: {
      bg: "#0f1419",
      surface: "#1a222d",
      border: "#2d3a4a",
      text: "#f0f4f8",
      muted: "#8fa3b8",
      primary: "#0369a1",
      primaryHover: "#0284c7",
      primaryText: "#ffffff",
      accent: "#38bdf8",
    },
  },
  {
    slug: "healthcare",
    category: "industry",
    clientType: "healthcare",
    clientLabel: "Healthcare clinic",
    brand: "ClearPath Clinic",
    eyebrow: "Family medicine & dental · sample",
    headline: "Healthcare that respects your time — and your health.",
    subheadline:
      "Same-week appointments, online booking, and a team that explains options clearly. GP, dental, and preventive care under one roof.",
    cta: "Book an appointment",
    ctaSecondary: "Our services",
    features: [
      { title: "Online booking", description: "Choose doctor, service, and slot — reminders sent automatically." },
      { title: "Same-week availability", description: "Urgent and routine visits without months of waiting." },
      { title: "Integrated records", description: "Dental and GP history in one place for continuity of care." },
    ],
    stats: [
      { value: "4.9", label: "Patient rating" },
      { value: "12", label: "Specialists" },
      { value: "7", label: "Days open" },
    ],
    steps: [
      { title: "Book online", description: "Pick service, provider, and time that works." },
      { title: "Visit the clinic", description: "Check in fast — minimal waiting, clear next steps." },
      { title: "Follow-up care", description: "Results, prescriptions, and recalls handled digitally." },
    ],
    testimonial: {
      quote: "Booked a dental check and GP follow-up in five minutes. The team actually listens — rare for a clinic this busy.",
      author: "Karolina Weiss",
      role: "Patient · Family of four",
    },
    trustLogos: ["NHS Partners", "Bupa", "Doctolib", "Zocdoc", "ISO 9001", "GDPR Ready"],
    theme: {
      bg: "#f0f9ff",
      surface: "#ffffff",
      border: "#bae6fd",
      text: "#0c4a6e",
      muted: "#64748b",
      primary: "#0284c7",
      primaryHover: "#0ea5e9",
      primaryText: "#ffffff",
      accent: "#06b6d4",
    },
  },
  {
    slug: "education",
    category: "industry",
    clientType: "education",
    clientLabel: "Education company",
    brand: "BrightMind Academy",
    eyebrow: "Online courses & tutoring · sample",
    headline: "Learn skills that actually move your career forward.",
    subheadline:
      "Live cohorts, on-demand lessons, and 1:1 mentoring in tech, languages, and business — built for working professionals.",
    cta: "Browse courses",
    ctaSecondary: "Free trial lesson",
    features: [
      { title: "Live + on-demand", description: "Join live sessions or learn at your pace — same quality either way." },
      { title: "Expert instructors", description: "Practitioners who teach what they do daily, not theory-only academics." },
      { title: "Career outcomes", description: "Projects, certificates, and portfolio work employers recognize." },
    ],
    stats: [
      { value: "8k+", label: "Graduates" },
      { value: "40+", label: "Courses" },
      { value: "92%", label: "Completion rate" },
    ],
    steps: [
      { title: "Pick a path", description: "Course, bootcamp, or 1:1 tutoring — matched to your goal." },
      { title: "Learn by doing", description: "Projects, feedback, and peer groups keep you on track." },
      { title: "Apply it", description: "Certificate, portfolio, and career support when you finish." },
    ],
    testimonial: {
      quote: "The data analytics cohort paid for itself in two months. Clear curriculum, real datasets, and instructors who answer fast.",
      author: "Daniel Okonkwo",
      role: "Graduate · Career switcher",
    },
    trustLogos: ["Coursera", "Udemy", "LinkedIn Learning", "Google", "Microsoft", "British Council"],
    theme: {
      bg: "#fefce8",
      surface: "#ffffff",
      border: "#fde047",
      text: "#422006",
      muted: "#78716c",
      primary: "#ca8a04",
      primaryHover: "#eab308",
      primaryText: "#422006",
      accent: "#f97316",
    },
  },
  {
    slug: "construction",
    category: "industry",
    clientType: "construction",
    clientLabel: "Construction company",
    brand: "Stonebridge Builders",
    eyebrow: "Residential & commercial build · sample",
    headline: "Built to spec. Delivered on schedule. No surprises.",
    subheadline:
      "Renovations, extensions, and commercial fit-outs across the region. Fixed timelines, transparent quotes, and site managers you can reach.",
    cta: "Request a quote",
    ctaSecondary: "View projects",
    features: [
      { title: "Fixed-scope quotes", description: "Line-item estimates so you know exactly what you're paying for." },
      { title: "Dedicated site manager", description: "One contact from kickoff to handover — daily updates available." },
      { title: "Quality materials", description: "Vetted suppliers and inspections at every milestone." },
    ],
    stats: [
      { value: "150+", label: "Projects completed" },
      { value: "15", label: "Years experience" },
      { value: "0", label: "Hidden fees" },
    ],
    steps: [
      { title: "Site visit", description: "Measure, discuss scope, and flag constraints early." },
      { title: "Quote & plan", description: "Timeline, materials, and permits agreed in writing." },
      { title: "Build & handover", description: "Weekly progress, snag list, and keys when it's right." },
    ],
    testimonial: {
      quote: "Our office fit-out finished two days early and on budget. Stonebridge's site manager made the whole thing painless.",
      author: "Piotr Kamiński",
      role: "Facilities director · Retail chain",
    },
    trustLogos: ["ISO 45001", "Federation of Master Builders", "CE Mark", "Knauf", "Bosch", "Sika"],
    theme: {
      bg: "#1c1917",
      surface: "#292524",
      border: "#44403c",
      text: "#fafaf9",
      muted: "#a8a29e",
      primary: "#ea580c",
      primaryHover: "#f97316",
      primaryText: "#ffffff",
      accent: "#fbbf24",
    },
  },
  {
    slug: "automotive",
    category: "industry",
    clientType: "automotive",
    clientLabel: "Automotive dealer",
    brand: "Axis Motors",
    eyebrow: "New & certified pre-owned · sample",
    headline: "Find your next car — transparent pricing, zero pressure.",
    subheadline:
      "Premium brands, certified pre-owned stock, and financing options explained in plain language. Test drives booked online.",
    cta: "Browse inventory",
    ctaSecondary: "Book test drive",
    features: [
      { title: "Live inventory", description: "Search by model, budget, and features — updated daily." },
      { title: "Certified pre-owned", description: "Multi-point inspection and warranty on every used vehicle." },
      { title: "Finance & trade-in", description: "Instant estimates and clear monthly payment breakdowns." },
    ],
    stats: [
      { value: "200+", label: "Cars in stock" },
      { value: "48h", label: "Finance approval" },
      { value: "4.7", label: "Dealer rating" },
    ],
    steps: [
      { title: "Search online", description: "Filter inventory and compare specs side by side." },
      { title: "Test drive", description: "Book a slot — car prepped and ready when you arrive." },
      { title: "Drive away", description: "Finance, trade-in, and registration handled in-house." },
    ],
    testimonial: {
      quote: "Found the exact spec online, test drove Saturday, picked it up Tuesday. No upsell nonsense — just straight answers.",
      author: "James Mitchell",
      role: "Buyer · Certified pre-owned SUV",
    },
    trustLogos: ["BMW", "Mercedes-Benz", "Audi", "Volkswagen", "AutoTrader", "CarGurus"],
    theme: {
      bg: "#09090b",
      surface: "#18181b",
      border: "#3f3f46",
      text: "#fafafa",
      muted: "#a1a1aa",
      primary: "#dc2626",
      primaryHover: "#ef4444",
      primaryText: "#ffffff",
      accent: "#71717a",
    },
  },
  {
    slug: "travel",
    category: "industry",
    clientType: "travel",
    clientLabel: "Travel agency",
    brand: "Horizon Voyages",
    eyebrow: "Custom trips & group travel · sample",
    headline: "Trips designed around how you actually want to travel.",
    subheadline:
      "Honeymoons, family holidays, and corporate retreats — flights, hotels, and experiences planned by people who've been there.",
    cta: "Plan your trip",
    ctaSecondary: "Popular destinations",
    features: [
      { title: "Tailored itineraries", description: "Not package tours — routes built around your dates, budget, and interests." },
      { title: "24/7 trip support", description: "Real humans on WhatsApp when flights shift or plans change." },
      { title: "Group & corporate", description: "Retreats, incentives, and team offsites with logistics handled end-to-end." },
    ],
    stats: [
      { value: "60+", label: "Destinations" },
      { value: "2k+", label: "Trips planned" },
      { value: "4.9", label: "Traveler rating" },
    ],
    steps: [
      { title: "Share your brief", description: "Dates, budget, vibe, and must-sees — we ask the right questions." },
      { title: "Review your itinerary", description: "Flights, stays, transfers, and activities in one document." },
      { title: "Travel with backup", description: "Documents, insurance, and support before and during the trip." },
    ],
    testimonial: {
      quote: "They planned our two-week Japan trip down to the rail passes and ryokan stays. When our flight moved, they rebooked before we even noticed.",
      author: "Sophie & Mark Chen",
      role: "Honeymoon travelers",
    },
    trustLogos: ["Skyscanner", "Booking.com", "Amadeus", "IATA", "TripAdvisor", "Airbnb"],
    theme: {
      bg: "#042f2e",
      surface: "#0d4f4f",
      border: "#115e59",
      text: "#f0fdfa",
      muted: "#5eead4",
      primary: "#0d9488",
      primaryHover: "#14b8a6",
      primaryText: "#ffffff",
      accent: "#fbbf24",
    },
  },
  {
    slug: "finance",
    category: "industry",
    clientType: "finance",
    clientLabel: "Finance & accounting firm",
    brand: "Summit Advisory",
    eyebrow: "Accounting & business advisory · sample",
    headline: "Numbers clear. Tax optimized. Decisions confident.",
    subheadline:
      "Bookkeeping, tax filing, and CFO-level advisory for SMEs and founders — proactive, not just reactive compliance.",
    cta: "Book a discovery call",
    ctaSecondary: "Our services",
    features: [
      { title: "Monthly bookkeeping", description: "Clean books, reconciled accounts, and dashboards you actually read." },
      { title: "Tax planning", description: "Legitimate optimization before year-end — not last-minute panic filing." },
      { title: "Growth advisory", description: "Cash flow, hiring, and expansion decisions backed by your numbers." },
    ],
    stats: [
      { value: "300+", label: "Business clients" },
      { value: "€50M+", label: "Managed annually" },
      { value: "10", label: "Senior advisors" },
    ],
    steps: [
      { title: "Discovery call", description: "Understand structure, pain points, and compliance needs." },
      { title: "Onboard & clean up", description: "Systems connected, backlog cleared, baseline established." },
      { title: "Ongoing partnership", description: "Monthly closes, quarterly reviews, and tax season handled." },
    ],
    testimonial: {
      quote: "Summit caught a VAT issue before audit season and saved us a painful correction. They're part of our leadership rhythm now.",
      author: "Anika Bergström",
      role: "CFO · E-commerce group",
    },
    trustLogos: ["Xero", "QuickBooks", "Stripe", "Deloitte", "PwC Network", "ACCA"],
    theme: {
      bg: "#0f172a",
      surface: "#1e293b",
      border: "#334155",
      text: "#f8fafc",
      muted: "#94a3b8",
      primary: "#1d4ed8",
      primaryHover: "#2563eb",
      primaryText: "#ffffff",
      accent: "#22c55e",
    },
  },
  {
    slug: "cleaning",
    category: "industry",
    clientType: "cleaning",
    clientLabel: "Cleaning & home services",
    brand: "PureHome Services",
    eyebrow: "Residential & office cleaning · sample",
    headline: "A cleaner home or office — booked in two minutes.",
    subheadline:
      "Vetted teams, eco-friendly products, and recurring or one-off cleans. Apartments, houses, and small offices across the city.",
    cta: "Book a clean",
    ctaSecondary: "See pricing",
    features: [
      { title: "Instant online booking", description: "Pick service, size, and time — confirmation in seconds." },
      { title: "Vetted cleaners", description: "Background-checked teams with consistent ratings and supervision." },
      { title: "Flexible plans", description: "One-off deep cleans, weekly maintenance, or move-in/move-out." },
    ],
    stats: [
      { value: "12k+", label: "Cleans completed" },
      { value: "4.8", label: "Average rating" },
      { value: "100%", label: "Satisfaction guarantee" },
    ],
    steps: [
      { title: "Choose your service", description: "Standard, deep clean, or office — add extras if needed." },
      { title: "Pick a time", description: "Real-time availability with your preferred team when possible." },
      { title: "Enjoy the result", description: "Pay online, rate the visit, and rebook in one tap." },
    ],
    testimonial: {
      quote: "Bi-weekly cleans for our flat — always on time, always thorough. Booking takes less time than ordering coffee.",
      author: "Marta Silva",
      role: "Subscriber · 2-bed apartment",
    },
    trustLogos: ["TaskRabbit", "Helpling", "Molly Maid", "Ecover", "Method", "Trustpilot"],
    theme: {
      bg: "#ecfdf5",
      surface: "#ffffff",
      border: "#a7f3d0",
      text: "#064e3b",
      muted: "#64748b",
      primary: "#059669",
      primaryHover: "#10b981",
      primaryText: "#ffffff",
      accent: "#34d399",
    },
  },
  {
    slug: "photography",
    category: "industry",
    clientType: "photography",
    clientLabel: "Photography studio",
    brand: "Lens & Light Co.",
    eyebrow: "Wedding & brand photography · sample",
    headline: "Images that feel natural — and look unforgettable.",
    subheadline:
      "Weddings, portraits, and brand shoots for businesses that care how they're seen. Editorial style, fast delivery, clear packages.",
    cta: "View portfolio",
    ctaSecondary: "Check availability",
    features: [
      { title: "Curated portfolio", description: "Browse weddings, brands, and portraits — see the style before you book." },
      { title: "Transparent packages", description: "Hours, deliverables, and usage rights listed upfront — no vague quotes." },
      { title: "Fast turnaround", description: "Preview gallery within days; full edit on an agreed timeline." },
    ],
    stats: [
      { value: "400+", label: "Events shot" },
      { value: "72h", label: "Preview delivery" },
      { value: "5.0", label: "Couples rating" },
    ],
    steps: [
      { title: "Check availability", description: "Date, location, and type of shoot — we confirm within 24h." },
      { title: "Plan the day", description: "Shot list, timeline, and locations agreed before the event." },
      { title: "Receive your gallery", description: "Online gallery, downloads, and print options when you're ready." },
    ],
    testimonial: {
      quote: "Our wedding photos look like a magazine spread but still feel like us. They nailed the golden hour shots we wanted.",
      author: "Elena & Marco",
      role: "Wedding clients · Tuscany",
    },
    trustLogos: ["Vogue Weddings", "Canon", "Sony Alpha", "Adobe Lightroom", "The Knot", "WedShoots"],
    theme: {
      bg: "#18181b",
      surface: "#27272a",
      border: "#3f3f46",
      text: "#fafafa",
      muted: "#d4d4d8",
      primary: "#fafafa",
      primaryHover: "#e4e4e7",
      primaryText: "#18181b",
      accent: "#f472b6",
    },
  },
]
